export const songDetails1 = {
  "album": {
    "album_type": "album",
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/6fynenqBn7lrlAgVCw5YnB"
        },
        "href": "https://api.spotify.com/v1/artists/6fynenqBn7lrlAgVCw5YnB",
        "id": "6fynenqBn7lrlAgVCw5YnB",
        "name": "Moderator",
        "type": "artist",
        "uri": "spotify:artist:6fynenqBn7lrlAgVCw5YnB"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "ZA"
    ],
    "external_urls": {
      "spotify": "https://open.spotify.com/album/6MhR8bYMatTqRoFdFnyqr0"
    },
    "href": "https://api.spotify.com/v1/albums/6MhR8bYMatTqRoFdFnyqr0",
    "id": "6MhR8bYMatTqRoFdFnyqr0",
    "images": [
      {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b27331073ba528a43985280d4dc6",
        "width": 640
      },
      {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e0231073ba528a43985280d4dc6",
        "width": 300
      },
      {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d0000485131073ba528a43985280d4dc6",
        "width": 64
      }
    ],
    "name": "The World Within",
    "release_date": "2015-02-19",
    "release_date_precision": "day",
    "total_tracks": 9,
    "type": "album",
    "uri": "spotify:album:6MhR8bYMatTqRoFdFnyqr0"
  },
  "artists": [
    {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/6fynenqBn7lrlAgVCw5YnB"
      },
      "href": "https://api.spotify.com/v1/artists/6fynenqBn7lrlAgVCw5YnB",
      "id": "6fynenqBn7lrlAgVCw5YnB",
      "name": "Moderator",
      "type": "artist",
      "uri": "spotify:artist:6fynenqBn7lrlAgVCw5YnB"
    },
  ],
  "available_markets": [
    "AD",
    "AE",
    "AL",
    "AR",
    "AT",
    "AU",
    "BA",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HR",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "KZ",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MD",
    "ME",
    "MK",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "RU",
    "SA",
    "SE",
    "SG",
    "SI",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "UA",
    "US",
    "UY",
    "VN",
    "ZA"
  ],
  "disc_number": 1,
  "duration_ms": 207283,
  "explicit": false,
  "external_ids": {
    "isrc": "TCACD1599893"
  },
  "external_urls": {
    "spotify": "https://open.spotify.com/track/1SL5a4aSDTmwcwO8Dm8lWA"
  },
  "href": "https://api.spotify.com/v1/tracks/1SL5a4aSDTmwcwO8Dm8lWA",
  "id": "1SL5a4aSDTmwcwO8Dm8lWA",
  "is_local": false,
  "name": "Words Remain",
  "popularity": 55,
  "preview_url": "https://p.scdn.co/mp3-preview/6400f9c978f4733591f8fef7ea34e5c0b3c41cb3?cid=47e2c485aa3c47a6a39e71bb2fcf4da4",
  "track_number": 3,
  "type": "track",
  "uri": "spotify:track:1SL5a4aSDTmwcwO8Dm8lWA"
}

export const songDetails2 = {
  "album": {
    "album_type": "album",
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/2wOqMjp9TyABvtHdOSOTUS"
        },
        "href": "https://api.spotify.com/v1/artists/2wOqMjp9TyABvtHdOSOTUS",
        "id": "2wOqMjp9TyABvtHdOSOTUS",
        "name": "Ludwig van Beethoven",
        "type": "artist",
        "uri": "spotify:artist:2wOqMjp9TyABvtHdOSOTUS"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/4LYCuV8d6rylb6zjv2k03l"
        },
        "href": "https://api.spotify.com/v1/artists/4LYCuV8d6rylb6zjv2k03l",
        "id": "4LYCuV8d6rylb6zjv2k03l",
        "name": "Paul Lewis",
        "type": "artist",
        "uri": "spotify:artist:4LYCuV8d6rylb6zjv2k03l"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CA",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    "external_urls": {
      "spotify": "https://open.spotify.com/album/4bNwPPpk01D8pVV9IFSBde"
    },
    "href": "https://api.spotify.com/v1/albums/4bNwPPpk01D8pVV9IFSBde",
    "id": "4bNwPPpk01D8pVV9IFSBde",
    "images": [
      {
        "height": 640,
        "url": "https://i.scdn.co/image/ab67616d0000b2735fbde95caaf1018f9af50f71",
        "width": 640
      },
      {
        "height": 300,
        "url": "https://i.scdn.co/image/ab67616d00001e025fbde95caaf1018f9af50f71",
        "width": 300
      },
      {
        "height": 64,
        "url": "https://i.scdn.co/image/ab67616d000048515fbde95caaf1018f9af50f71",
        "width": 64
      }
    ],
    "name": "Beethoven: Piano Sonatas, Vol.3",
    "release_date": "2007-09-25",
    "release_date_precision": "day",
    "total_tracks": 32,
    "type": "album",
    "uri": "spotify:album:4bNwPPpk01D8pVV9IFSBde"
  },
  "artists": [
    {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/2wOqMjp9TyABvtHdOSOTUS"
      },
      "href": "https://api.spotify.com/v1/artists/2wOqMjp9TyABvtHdOSOTUS",
      "id": "2wOqMjp9TyABvtHdOSOTUS",
      "name": "Ludwig van Beethoven",
      "type": "artist",
      "uri": "spotify:artist:2wOqMjp9TyABvtHdOSOTUS"
    },
    {
      "external_urls": {
        "spotify": "https://open.spotify.com/artist/4LYCuV8d6rylb6zjv2k03l"
      },
      "href": "https://api.spotify.com/v1/artists/4LYCuV8d6rylb6zjv2k03l",
      "id": "4LYCuV8d6rylb6zjv2k03l",
      "name": "Paul Lewis",
      "type": "artist",
      "uri": "spotify:artist:4LYCuV8d6rylb6zjv2k03l"
    }
  ],
  "available_markets": [
    "AD",
    "AE",
    "AL",
    "AR",
    "AT",
    "AU",
    "BA",
    "BE",
    "BG",
    "BH",
    "BO",
    "BR",
    "BY",
    "CA",
    "CH",
    "CL",
    "CO",
    "CR",
    "CY",
    "CZ",
    "DE",
    "DK",
    "DO",
    "DZ",
    "EC",
    "EE",
    "EG",
    "ES",
    "FI",
    "FR",
    "GB",
    "GR",
    "GT",
    "HK",
    "HN",
    "HR",
    "HU",
    "ID",
    "IE",
    "IL",
    "IN",
    "IS",
    "IT",
    "JO",
    "JP",
    "KW",
    "KZ",
    "LB",
    "LI",
    "LT",
    "LU",
    "LV",
    "MA",
    "MC",
    "MD",
    "ME",
    "MK",
    "MT",
    "MX",
    "MY",
    "NI",
    "NL",
    "NO",
    "NZ",
    "OM",
    "PA",
    "PE",
    "PH",
    "PL",
    "PS",
    "PT",
    "PY",
    "QA",
    "RO",
    "RS",
    "RU",
    "SA",
    "SE",
    "SG",
    "SI",
    "SK",
    "SV",
    "TH",
    "TN",
    "TR",
    "TW",
    "UA",
    "US",
    "UY",
    "VN",
    "XK",
    "ZA"
  ],
  "disc_number": 1,
  "duration_ms": 448040,
  "explicit": false,
  "external_ids": {
    "isrc": "FRZ140630050"
  },
  "external_urls": {
    "spotify": "https://open.spotify.com/track/5C0KEAjO1qBZkTjqiYtGry"
  },
  "href": "https://api.spotify.com/v1/tracks/5C0KEAjO1qBZkTjqiYtGry",
  "id": "5C0KEAjO1qBZkTjqiYtGry",
  "is_local": false,
  "name": "Sonata No. 2 in A Major, Op. 2 No. 2: I. Allegro vivace",
  "popularity": 25,
  "preview_url": "https://p.scdn.co/mp3-preview/7699e34fa2fa5d3ff2a048bf0f48cf281a055339?cid=47e2c485aa3c47a6a39e71bb2fcf4da4",
  "track_number": 5,
  "type": "track",
  "uri": "spotify:track:5C0KEAjO1qBZkTjqiYtGry"
}
